import javax.swing.*;
import javax.swing.plaf.basic.BasicBorders;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

public class main_game {
    private JFrame main_frame;
    private JPanel main_panel;
    private JPanel main_right_panel;
    private JPanel main_bottom_panel;
    private JPanel board_panel;
    private JLabel bottom_panel_label;
    private JPanel top_main_right_panel;
    private JPanel dice_panel;
    private JLabel dice_num_label;
    private JButton rollDiceButton;
    private JPanel bottom_main_right_panel;
    private JButton RESETButton;
    private JButton button0;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button7;
    private JButton button8;
    private JButton button9;
    private JButton button10;
    private JButton button11;
    private JButton button6;
    private JButton button12;
    private JButton button99;
    private JButton OPTIONSButton;
    private JButton SAVEANDEXITButton;
    private JButton EXITButton;
    Random rand = new Random();
    public settings s;
    int dice;

    public main_game() {
        main_frame = new JFrame("Malefiz Game");
        main_frame.add(main_panel);
        main_frame.setMinimumSize(new Dimension(750, 750));
        main_frame.setLocation
                ((Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 340,
                        (Toolkit.getDefaultToolkit().getScreenSize().height / 2) - 315);
        main_frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        main_frame.validate();
        main_frame.repaint();
        System.out.println("Was here");
        rollDiceButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int dice = rand.nextInt(7);
                System.out.println("Dice: " + dice);
                dice_num_label = new JLabel();
                dice_num_label.setText(dice + "");
                dice_num_label.repaint();
                dice_num_label.validate();
                dice_num_label.updateUI();
                dice_num_label.paintImmediately(dice_num_label.getVisibleRect());
                dice_panel.repaint();
                dice_panel.validate();
            }
        });
        EXITButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(50);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main_panel = new JPanel();
        main_panel.setLayout(new BorderLayout(0, 0));
        main_right_panel = new JPanel();
        main_right_panel.setLayout(new BorderLayout(0, 0));
        main_panel.add(main_right_panel, BorderLayout.EAST);
        top_main_right_panel = new JPanel();
        top_main_right_panel.setLayout(new GridBagLayout());
        main_right_panel.add(top_main_right_panel, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Chiller", Font.BOLD, 48, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Malefiz Game");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        top_main_right_panel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 25;
        top_main_right_panel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        top_main_right_panel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        top_main_right_panel.add(spacer3, gbc);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, -1, 20, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setHorizontalAlignment(0);
        label2.setHorizontalTextPosition(0);
        label2.setText("Group 14");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        top_main_right_panel.add(label2, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 80;
        top_main_right_panel.add(spacer4, gbc);
        dice_panel = new JPanel();
        dice_panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        dice_panel.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        top_main_right_panel.add(dice_panel, gbc);
        dice_num_label = new JLabel();
        dice_num_label.setEnabled(false);
        Font dice_num_labelFont = this.$$$getFont$$$(null, Font.BOLD, 72, dice_num_label.getFont());
        if (dice_num_labelFont != null) dice_num_label.setFont(dice_num_labelFont);
        dice_num_label.setHorizontalAlignment(0);
        dice_num_label.setHorizontalTextPosition(0);
        dice_num_label.setText("0");
        dice_panel.add(dice_num_label);
        rollDiceButton = new JButton();
        rollDiceButton.setBackground(new Color(-13283793));
        rollDiceButton.setForeground(new Color(-723724));
        rollDiceButton.setText("roll dice");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 25;
        top_main_right_panel.add(rollDiceButton, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 25;
        top_main_right_panel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        top_main_right_panel.add(spacer6, gbc);
        bottom_main_right_panel = new JPanel();
        bottom_main_right_panel.setLayout(new GridBagLayout());
        main_right_panel.add(bottom_main_right_panel, BorderLayout.SOUTH);
        RESETButton = new JButton();
        RESETButton.setText("RESET");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bottom_main_right_panel.add(RESETButton, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bottom_main_right_panel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        bottom_main_right_panel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bottom_main_right_panel.add(spacer9, gbc);
        OPTIONSButton = new JButton();
        OPTIONSButton.setText("OPTIONS");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bottom_main_right_panel.add(OPTIONSButton, gbc);
        SAVEANDEXITButton = new JButton();
        SAVEANDEXITButton.setText("SAVE AND EXIT");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bottom_main_right_panel.add(SAVEANDEXITButton, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        bottom_main_right_panel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        bottom_main_right_panel.add(spacer11, gbc);
        EXITButton = new JButton();
        EXITButton.setText("EXIT");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bottom_main_right_panel.add(EXITButton, gbc);
        main_bottom_panel = new JPanel();
        main_bottom_panel.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 10));
        main_bottom_panel.setBackground(new Color(-11776948));
        main_panel.add(main_bottom_panel, BorderLayout.SOUTH);
        bottom_panel_label = new JLabel();
        bottom_panel_label.setForeground(new Color(-3092272));
        bottom_panel_label.setText("This will show which players turn it is");
        bottom_panel_label.setToolTipText("Turn Indicator");
        main_bottom_panel.add(bottom_panel_label);
        board_panel = new JPanel();
        board_panel.setLayout(new GridBagLayout());
        board_panel.setBackground(new Color(-263173));
        main_panel.add(board_panel, BorderLayout.CENTER);
        button0 = new JButton();
        button0.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button0, gbc);
        button1 = new JButton();
        button1.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button1, gbc);
        button2 = new JButton();
        button2.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button2, gbc);
        button3 = new JButton();
        button3.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button3, gbc);
        button4 = new JButton();
        button4.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button4, gbc);
        button5 = new JButton();
        button5.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button5, gbc);
        button7 = new JButton();
        button7.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button7, gbc);
        button8 = new JButton();
        button8.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button8, gbc);
        button9 = new JButton();
        button9.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button9, gbc);
        button10 = new JButton();
        button10.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button10, gbc);
        button11 = new JButton();
        button11.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button11, gbc);
        button6 = new JButton();
        button6.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button6, gbc);
        button12 = new JButton();
        button12.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button12, gbc);
        button99 = new JButton();
        button99.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        board_panel.add(button99, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("This is a test board, to see how backend function. ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 5;
        gbc.anchor = GridBagConstraints.WEST;
        board_panel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("The final version is yet to come.");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 5;
        gbc.anchor = GridBagConstraints.WEST;
        board_panel.add(label4, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        board_panel.add(spacer12, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main_panel;
    }

    void init() {
        this.$$$setupUI$$$();
        System.out.println("<<<MAIN GAME SEQUENCE>>>");

        main_frame.setVisible(true);

    }
}
